include: package:very_good_analysis/analysis_options.9.0.0.yaml
ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
linter:
  rules:
    avoid_print: false
    public_member_api_docs: false
    document_ignores: false
    avoid_catches_without_on_clauses: false
formatter:
  page_width: 80
analyzer:
  errors:
    specify_nonobvious_property_types: ignore
